apiVersion: v1
kind: Service
metadata:
  name: gluco-mlops-service
spec:
  type: NodePort
  selector:
    app: gluco-mlops-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
      nodePort: 30080
